apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  destination:
    namespace: gitlab
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.gitlab.io/'
    targetRevision: 5.5.2
    chart: gitlab
    helm:
      valueFiles:
        - values.yaml
      values: |
        # https://gitlab.com/gitlab-org/charts/gitlab/
        global:
          edition: ce
          hosts:
            domain: allnice.eu
            gitlab:
              name: gitlab.allnice.eu
              https: true
            registry:
              name: registry.allnice.eu
              https: true
            minio:
              name: minio.allnice.eu
              https: true
            smartcard:
              name: smartcard.allnice.eu
            kas:
              name: kas.allnice.eu
            pages:
              name: pages.allnice.eu
              https: true
          ingress:
            enabled: false
            configureCertmanager: false
            annotations: 
              kubernetes.io/tls-acme: true
          time_zone: CET

        upgradeCheck:
          enabled: false

        certmanager:
          install: false
        certmanager-issuer:
          email: letsencrypt@allnice.eu
        nginx-ingress:
          enabled: false

        postgresql:
          image:
            tag: 14.1.0

        shared-secrets:
          enabled: false
          rbac:
            create: true

        grafana:
          enabled: false

        # CUSTOM - Required for separately managed certmanager
        registry:
          ingress:
            tls:
              secretName: ingress-cert-registry

        # CUSTOM - Required for separately managed certmanager
        minio:
          ingress:
            tls:
              secretName: ingress-cert-minio

        # CUSTOM - Required for separately managed certmanager
        gitlab:
          gitlab-pages:
            ingress:
              tls:
                secretName: ingress-cert-gitlab-wc
          webservice:
            ingress:
              path: 
              tls:
                secretName: ingress-cert-gitlab
          toolbox:
            replicas: 1
            antiAffinityLabels:
              matchLabels:
                app: 'gitaly'
          migrations:
            enabled: true

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
